apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  serviceName: postgresql
  selector:
   matchLabels:
    app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.POSTGRES_USER }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.POSTGRES_PASSWORD }}

          volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
    ports:
    - name: postgresql
      port: {{ .Values.postgresql.containerPort }}
      targetPort: {{ .Values.postgresql.containerPort }}
    clusterIP: None
    selector:
      app: postgresql
