apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.POSTGRES_USER | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.POSTGRES_DB | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.POSTGRES_PASSWORD | quote }}
          ports:
            - containerPort: {{ .Values.postgresql.containerPort }}
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: postgres-data
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
  namespace: {{ .Release.Namespace }}
spec:
    ports:
    - name: postgresql
      port: {{ .Values.postgresql.containerPort }}
      targetPort: {{ .Values.postgresql.containerPort }}
    clusterIP: None
    selector:
      app: postgresql
